[project]
title = "TSSW Developer Guide"
copyright = "2024 Association of Universities for Research in Astronomy, Inc. (AURA)"
base_url = "https://tssw-developer.lsst.io"
github_url = "https://github.com/lsst-ts/tssw_developer_guide"

[sphinx]
extensions = ["sphinx.ext.autosectionlabel"]

[sphinx.intersphinx.projects]
dm_developer_guide = "https://developer.lsst.io"
